conda_home: '~/.conda/envs'
matlab_home: '/usr/local/matlab2017b'

scmh:
  batch:
    executor_env_name: 'matlab'
    learning_principle: 'shallow'
  dcmh:
    executor_env_name: 'cmr_toolbox_tf'
    learning_principle: 'deep'

ucmh:
  djsrh:
    executor_env_name: 'cmr_toolbox_torch'
    learning_principle: 'deep'
